import {Event, TeamEventHeader} from '@/src/types/event';

export const eventData: Array<Event | TeamEventHeader> = [
  {
    team_id: 124,
    type: 'header',
    name: 'Team',
  },
  {
    event_id: 2003,
    event_date: '8/20/1999',
    start_time: '2:00 PM',
    end_time: null,
    description: null,
    season: '1999-2000',
    location: 'CARSTENS FIELD',
    place: 'H',
    opponent: 'Purple And White Scrimmage',
    kind: 'Scrimmage',
    team_id: 124,
    url: '',
    short_name: 'Scrimmage',
    results: [],
    cancellation_status: false,
    conference: false,
  },
  {
    event_id: 2013,
    event_date: '8/24/1999',
    start_time: '4:00 PM',
    end_time: null,
    description: null,
    season: '1999-2000',
    location: 'CARSTENS FIELD',
    place: 'H',
    opponent: 'Intersquad Scrimmage',
    kind: 'Scrimmage',
    team_id: 124,
    url: '',
    short_name: 'Scrimmage',
    results: [],
    cancellation_status: false,
    conference: false,
  },
  {
    event_id: 2,
    event_date: '9/16/2017',
    start_time: 'TBA',
    end_time: '2:00 AM',
    description: null,
    season: '2017-2018',
    location: 'Parkway Christian',
    place: 'A',
    opponent: 'Parkway Christian Tournament',
    kind: 'Game',
    team_id: 41,
    url: '',
    short_name: 'at Parkway Christian Tournament',
    results: [],
    cancellation_status: false,
    conference: false,
  },
  {
    event_id: 3,
    event_date: '9/19/2017',
    start_time: '6:30 PM',
    end_time: '8:30 PM',
    description: null,
    season: '2017-2018',
    location: 'High School Gym',
    place: 'H',
    opponent: 'Lutheran High School  Northwest',
    kind: 'Game',
    team_id: 41,
    url: '',
    short_name: 'vs Lutheran High School  Northwest',
    results: [],
    cancellation_status: false,
    conference: false,
  },
];
